global using Domain.Contracts;
global using Domain.Entities;
global using Shared.Common;
global using AutoMapper;
global using Services.Abstraction.Contracts;
global using Domain.Exceptions;
global using Shared.Dtos;
global using Shared;
global using Services.Specifications.FacultyMemberDataModule;
global using Domain.Entities.FacultyMemberDataModule;
global using Shared.Dtos.IdentityModule;
using Services.Global;