namespace Shared.Enums.Logging
{
	public enum CategoryAction
	{
		CheckNationalNumber = 1,
		UserRegistration = 2,
		SendEmail = 3,
		UserLogin = 4,
		SendCredentialsByEmail = 5,
		SendOTP = 6,
		ResetPassword = 7,
		Initialize = 8,
		GetConnection = 9,
		Dispose = 10,
		DeclareQueueAndExchange = 11,
		PublishMessage = 12,
		ConsumeMessages = 13,
		MessageHandling = 14,
		BackgroundExecution = 15,
		StopBackgroundExecution = 16,
		ExternalDataProcessing = 17,
		PersonalDataActions = 18,
		ContactDataActions = 19,
		IdentificationCardDataActions = 20,
		SocialMediaDataActions = 21,
		ProfileDashboardDataActions = 22,
		EnsureOwnership = 23,
		ContributionsToCommunityServiceActions = 24,
		ContributionsToUniversityActions = 25,
		ParticipationInQualityWorksActions = 26,
		GeneralExperiencesActions = 27,
		TeachingExperiencesActions = 28,
		ScientificMissionsActions = 29,
		ConferencesAndSeminarsActions = 30,
		TrainingProgramsActions = 31,
		ManifestationsOfScientificAppreciationActions = 32,
	}
}
