// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Presistence.Data;

#nullable disable

namespace Presistence.Data.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20251122173707_FixMockUp")]
    partial class FixMockUp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.FacultyMemberDataModule.ContactData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("NVARCHAR(75)");

                    b.Property<string>("AlternativeEmail")
                        .HasColumnType("NVARCHAR(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FacultyMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FaxNumber")
                        .HasColumnType("NVARCHAR(150)");

                    b.Property<string>("HomePhoneNumber")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MainPhoneNumber")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("OfficialEmail")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(150)");

                    b.Property<string>("PersonalEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.Property<string>("WorkPhoneNumber")
                        .HasColumnType("NVARCHAR(50)");

                    b.HasKey("Id");

                    b.HasIndex("FacultyMemberId")
                        .IsUnique();

                    b.HasIndex("MainPhoneNumber");

                    b.HasIndex("OfficialEmail");

                    b.ToTable("ContactData");
                });

            modelBuilder.Entity("Domain.Entities.FacultyMemberDataModule.FacultyMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(150)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NationalNumber")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(14)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.HasIndex("NationalNumber")
                        .IsUnique();

                    b.ToTable("FacultyMembers");
                });

            modelBuilder.Entity("Domain.Entities.FacultyMemberDataModule.IdentificationCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademiaEdu")
                        .HasColumnType("NVARCHAR(Max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EKB")
                        .HasColumnType("NVARCHAR(Max)");

                    b.Property<Guid>("FacultyMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ORCID")
                        .HasColumnType("NVARCHAR(Max)");

                    b.Property<string>("ResearcherGate")
                        .HasColumnType("NVARCHAR(Max)");

                    b.Property<string>("ResearcherId")
                        .HasColumnType("NVARCHAR(Max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FacultyMemberId")
                        .IsUnique();

                    b.ToTable("IdentificationCards", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.FacultyMemberDataModule.PersonalData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccurateSpecialization")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("AuthorityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("Date");

                    b.Property<string>("BirthPlace")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CompositionTopics")
                        .HasColumnType("NVARCHAR(Max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FacultyMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GeneralSpecialization")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("MaritalStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NameInComposition")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TitleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UniversityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorityId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("FacultyMemberId")
                        .IsUnique();

                    b.HasIndex("FieldId");

                    b.HasIndex("GenderId");

                    b.HasIndex("MaritalStatusId");

                    b.HasIndex("TitleId");

                    b.HasIndex("UniversityId");

                    b.ToTable("PersonalData");
                });

            modelBuilder.Entity("Domain.Entities.FacultyMemberDataModule.SocialMediaPlatforms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Facebook")
                        .HasColumnType("NVARCHAR(Max)");

                    b.Property<Guid>("FacultyMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GoogleScholar")
                        .HasColumnType("NVARCHAR(Max)");

                    b.Property<string>("Instagram")
                        .HasColumnType("NVARCHAR(Max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LinkedIn")
                        .HasColumnType("NVARCHAR(Max)");

                    b.Property<string>("PersonalWebsite")
                        .HasColumnType("NVARCHAR(Max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Scopus")
                        .HasColumnType("NVARCHAR(Max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.Property<string>("X")
                        .HasColumnType("NVARCHAR(Max)");

                    b.Property<string>("YouTube")
                        .HasColumnType("NVARCHAR(Max)");

                    b.HasKey("Id");

                    b.HasIndex("FacultyMemberId")
                        .IsUnique();

                    b.ToTable("SocialMedia", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Lookup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValueAr")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ValueEn")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Lookups", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "BACHELOR",
                            SortOrder = 1,
                            Type = "AcademicQualification",
                            ValueAr = "ليسانس",
                            ValueEn = "Bachelor's degree",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "BACHELOR",
                            SortOrder = 2,
                            Type = "AcademicQualification",
                            ValueAr = "بكالوريوس",
                            ValueEn = "Bachelor's",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "HIGHER STUDIES",
                            SortOrder = 3,
                            Type = "AcademicQualification",
                            ValueAr = "دبلوم الدراسات العليا",
                            ValueEn = "Postgraduate Diploma",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111114"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "HIGHER STUDIES",
                            SortOrder = 4,
                            Type = "AcademicQualification",
                            ValueAr = "ماجستير",
                            ValueEn = "Master Degree",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111115"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "HIGHER STUDIES",
                            SortOrder = 5,
                            Type = "AcademicQualification",
                            ValueAr = "كورسات مكافئة للماجستير",
                            ValueEn = "Courses equivalent to a master's degree",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111116"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "HIGHER STUDIES",
                            SortOrder = 6,
                            Type = "AcademicQualification",
                            ValueAr = "الدكتوراه",
                            ValueEn = "PHD",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111117"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "HIGHER STUDIES",
                            SortOrder = 7,
                            Type = "AcademicQualification",
                            ValueAr = "دكتوراة العلوم",
                            ValueEn = "Ph.D. of Science",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111118"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "HIGHER STUDIES",
                            SortOrder = 8,
                            Type = "AcademicQualification",
                            ValueAr = "دكتوراة العلوم",
                            ValueEn = "Ph.D. of Science",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111119"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "HIGHER STUDIES",
                            SortOrder = 9,
                            Type = "AcademicQualification",
                            ValueAr = "العالمية",
                            ValueEn = "Global",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111120"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "HIGHER STUDIES",
                            SortOrder = 10,
                            Type = "AcademicQualification",
                            ValueAr = "الاجازة العالية",
                            ValueEn = "Higher Degree Qualification",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111121"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "HIGHER STUDIES",
                            SortOrder = 11,
                            Type = "AcademicQualification",
                            ValueAr = "الزمالة",
                            ValueEn = "Fellowship",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111122"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "HIGHER STUDIES",
                            SortOrder = 12,
                            Type = "AcademicQualification",
                            ValueAr = "دبلوم عام",
                            ValueEn = "General diploma",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111123"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "HIGHER STUDIES",
                            SortOrder = 13,
                            Type = "AcademicQualification",
                            ValueAr = "دبلوم خاص",
                            ValueEn = "Special diploma",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111124"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "HIGHER STUDIES",
                            SortOrder = 14,
                            Type = "AcademicQualification",
                            ValueAr = "دبلوم مهني",
                            ValueEn = "Professional diploma",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111125"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "HIGHER STUDIES",
                            SortOrder = 15,
                            Type = "AcademicQualification",
                            ValueAr = "دبلوم تفرغ",
                            ValueEn = "Sabbatical diploma",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111126"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "HIGHER STUDIES",
                            SortOrder = 16,
                            Type = "AcademicQualification",
                            ValueAr = "دبلوم تأهيلي",
                            ValueEn = "Qualifying diploma",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111127"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "HIGHER STUDIES",
                            SortOrder = 17,
                            Type = "AcademicQualification",
                            ValueAr = "الكانديدات",
                            ValueEn = "Candidae",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222221"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "EXCELLENT",
                            SortOrder = 1,
                            Type = "AcademicGrade",
                            ValueAr = "ممتاز مع مرتبة الشرف",
                            ValueEn = "Excellent with honors",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "EXCELLENT",
                            SortOrder = 2,
                            Type = "AcademicGrade",
                            ValueAr = "ممتاز",
                            ValueEn = "Excellent",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222223"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "VERY GOOD",
                            SortOrder = 3,
                            Type = "AcademicGrade",
                            ValueAr = "جيد جدا مع مرتبة الشرف",
                            ValueEn = "Very good with honors",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222224"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "VERY GOOD",
                            SortOrder = 4,
                            Type = "AcademicGrade",
                            ValueAr = "جيد جدا",
                            ValueEn = "Very good",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222225"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "GOOD",
                            SortOrder = 5,
                            Type = "AcademicGrade",
                            ValueAr = "جيد",
                            ValueEn = "Good",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222226"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "ACCEPTABLE",
                            SortOrder = 6,
                            Type = "AcademicGrade",
                            ValueAr = "مقبول",
                            ValueEn = "Acceptable",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222227"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "FAIL",
                            SortOrder = 7,
                            Type = "AcademicGrade",
                            ValueAr = "راسب",
                            ValueEn = "Fail",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333331"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "MISSION",
                            SortOrder = 1,
                            Type = "Dispatch",
                            ValueAr = "بعثة داخلية",
                            ValueEn = "Internal mission",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333332"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "MISSION",
                            SortOrder = 2,
                            Type = "Dispatch",
                            ValueAr = "بعثة خارجية",
                            ValueEn = "Foreign mission",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "SUPERVISION",
                            SortOrder = 3,
                            Type = "Dispatch",
                            ValueAr = "اشراف مشترك",
                            ValueEn = "Joint supervision",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333334"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "SCHOLARSHIP",
                            SortOrder = 4,
                            Type = "Dispatch",
                            ValueAr = "منحة شخصية",
                            ValueEn = "Personal scholarship",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444441"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "EMPLOYEMENT",
                            SortOrder = 1,
                            Type = "EmploymentDegrees",
                            ValueAr = "معيد",
                            ValueEn = "Demonstrator",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444442"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "EMPLOYEMENT",
                            SortOrder = 2,
                            Type = "EmploymentDegrees",
                            ValueAr = "مدرس مساعد",
                            ValueEn = "Assistant teacher",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444443"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "EMPLOYEMENT",
                            SortOrder = 3,
                            Type = "EmploymentDegrees",
                            ValueAr = "مدرس",
                            ValueEn = "Teacher",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "EMPLOYEMENT",
                            SortOrder = 4,
                            Type = "EmploymentDegrees",
                            ValueAr = "استاذ مساعد",
                            ValueEn = "Assistant professor",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444445"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "EMPLOYEMENT",
                            SortOrder = 5,
                            Type = "EmploymentDegrees",
                            ValueAr = "استاذ",
                            ValueEn = "Professor",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444446"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "EMPLOYEMENT",
                            SortOrder = 6,
                            Type = "EmploymentDegrees",
                            ValueAr = "استاذ متفرغ",
                            ValueEn = "Full-time professor",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444447"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "EMPLOYEMENT",
                            SortOrder = 7,
                            Type = "EmploymentDegrees",
                            ValueAr = "استاذ غير متفرغ",
                            ValueEn = "Part-time professor",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444448"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "EMPLOYEMENT",
                            SortOrder = 8,
                            Type = "EmploymentDegrees",
                            ValueAr = "زميل",
                            ValueEn = "Peer",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444449"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "EMPLOYEMENT",
                            SortOrder = 9,
                            Type = "EmploymentDegrees",
                            ValueAr = "استشاري مساعد",
                            ValueEn = "Assistant consultant",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444450"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "EMPLOYEMENT",
                            SortOrder = 10,
                            Type = "EmploymentDegrees",
                            ValueAr = "استشاري",
                            ValueEn = "Consultative",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444451"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "EMPLOYEMENT",
                            SortOrder = 11,
                            Type = "EmploymentDegrees",
                            ValueAr = "استاذ مساعد متفرغ",
                            ValueEn = "Full-time Assistant Professor",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444452"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "EMPLOYEMENT",
                            SortOrder = 12,
                            Type = "EmploymentDegrees",
                            ValueAr = "مدرس متفرغ",
                            ValueEn = "Full time teacher",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444453"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "EMPLOYEMENT",
                            SortOrder = 13,
                            Type = "EmploymentDegrees",
                            ValueAr = "استاذ مساعد لقب علمي",
                            ValueEn = "Assistant Professor (academic title)",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444454"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "EMPLOYEMENT",
                            SortOrder = 14,
                            Type = "EmploymentDegrees",
                            ValueAr = "استاذ لقب علمي",
                            ValueEn = "Professor is a scientific title",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444455"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "EMPLOYEMENT",
                            SortOrder = 15,
                            Type = "EmploymentDegrees",
                            ValueAr = "مساعد باحث",
                            ValueEn = "Research assistant",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444456"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "EMPLOYEMENT",
                            SortOrder = 16,
                            Type = "EmploymentDegrees",
                            ValueAr = "باحث مساعد",
                            ValueEn = "Assistant researcher",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444457"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "EMPLOYEMENT",
                            SortOrder = 17,
                            Type = "EmploymentDegrees",
                            ValueAr = "باحث",
                            ValueEn = "Researcher",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444458"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "EMPLOYEMENT",
                            SortOrder = 18,
                            Type = "EmploymentDegrees",
                            ValueAr = "باحث اول",
                            ValueEn = "Senior researcher",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444459"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "EMPLOYEMENT",
                            SortOrder = 19,
                            Type = "EmploymentDegrees",
                            ValueAr = "رئيس بحوث",
                            ValueEn = "Head of Research",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444460"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "EMPLOYEMENT",
                            SortOrder = 20,
                            Type = "EmploymentDegrees",
                            ValueAr = "استاذ مساعد غير متفرغ",
                            ValueEn = "Part-time Assistant Professor",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444461"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "EMPLOYEMENT",
                            SortOrder = 21,
                            Type = "EmploymentDegrees",
                            ValueAr = "زميل متفرغ",
                            ValueEn = "Full-time colleague",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444462"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "EMPLOYEMENT",
                            SortOrder = 22,
                            Type = "EmploymentDegrees",
                            ValueAr = "مدرس غير متفرغ",
                            ValueEn = "Part-time teacher",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444463"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "EMPLOYEMENT",
                            SortOrder = 23,
                            Type = "EmploymentDegrees",
                            ValueAr = "استاذ مشارك",
                            ValueEn = "Associate Professor",
                            VersionNo = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444464"),
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Helwan Faculty Portal System",
                            IsDeleted = false,
                            Key = "EMPLOYEMENT",
                            SortOrder = 24,
                            Type = "EmploymentDegrees",
                            ValueAr = "اخرى",
                            ValueEn = "Other",
                            VersionNo = 0
                        });
                });

            modelBuilder.Entity("Domain.Entities.MissionsModule.ConferencesAndSeminars", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("FacultyMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LocalOrInternational")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OrganizingAuthority")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("RoleOfParticipationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.HasKey("Id");

                    b.HasIndex("FacultyMemberId");

                    b.HasIndex("Name");

                    b.HasIndex("RoleOfParticipationId");

                    b.HasIndex("StartDate");

                    b.ToTable("ConferencesAndSeminars", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.MissionsModule.ScientificMissions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryOrCity")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("FacultyMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MissionName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("UniversityOrFaculty")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryOrCity");

                    b.HasIndex("FacultyMemberId");

                    b.HasIndex("MissionName");

                    b.HasIndex("StartDate");

                    b.ToTable("ScientificMissions", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.MissionsModule.TrainingPrograms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("FacultyMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OrganizingAuthority")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("ParticipationType")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("TrainingProgramName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FacultyMemberId");

                    b.HasIndex("StartDate");

                    b.HasIndex("TrainingProgramName");

                    b.ToTable("TrainingPrograms", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ProjectsAndCommitteesModule.CommitteesAndAssociations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DegreeOfSubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("FacultyMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NameOfCommitteeOrAssociation")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<Guid>("TypeOfCommitteeOrAssociationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DegreeOfSubscriptionId");

                    b.HasIndex("FacultyMemberId");

                    b.HasIndex("NameOfCommitteeOrAssociation");

                    b.HasIndex("StartDate");

                    b.HasIndex("TypeOfCommitteeOrAssociationId");

                    b.ToTable("CommitteesAndAssociations", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ProjectsAndCommitteesModule.ParticipationInMagazines", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FacultyMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NameOfMagazine")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TypeOfParticipationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.Property<string>("WebsiteOfMagazine")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.HasKey("Id");

                    b.HasIndex("FacultyMemberId");

                    b.HasIndex("NameOfMagazine");

                    b.HasIndex("TypeOfParticipationId");

                    b.ToTable("ParticipationInMagazines", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ProjectsAndCommitteesModule.Projects", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("FacultyMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FinancingAuthority")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LocalOrInternational")
                        .HasColumnType("int");

                    b.Property<string>("NameOfProject")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("ParticipationRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<Guid>("TypeOfProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FacultyMemberId");

                    b.HasIndex("NameOfProject");

                    b.HasIndex("ParticipationRoleId");

                    b.HasIndex("StartDate");

                    b.HasIndex("TypeOfProjectId");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ProjectsAndCommitteesModule.ReviewingArticles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Authority")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("FacultyMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("ReviewingDate")
                        .HasColumnType("date");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TitleOfArticle")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FacultyMemberId");

                    b.HasIndex("ReviewingDate");

                    b.HasIndex("TitleOfArticle");

                    b.ToTable("ReviewingArticles", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ScientificProgressionModule.AcademicQualifications", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryOrCity")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DateOfObtainingTheQualification")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DispatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FacultyMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("QualificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("UniversityOrFaculty")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryOrCity");

                    b.HasIndex("DateOfObtainingTheQualification");

                    b.HasIndex("DispatchId");

                    b.HasIndex("FacultyMemberId");

                    b.HasIndex("GradeId");

                    b.HasIndex("QualificationId");

                    b.ToTable("AcademicQualifications", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ScientificProgressionModule.AdministrativePositions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("FacultyMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FacultyMemberId");

                    b.HasIndex("Position");

                    b.HasIndex("StartDate");

                    b.ToTable("AdministrativePositions", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ScientificProgressionModule.JobRanks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DateOfJobRank")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FacultyMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("JobRankId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DateOfJobRank");

                    b.HasIndex("FacultyMemberId");

                    b.HasIndex("JobRankId");

                    b.ToTable("JobRanks", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.FacultyMemberDataModule.ContactData", b =>
                {
                    b.HasOne("Domain.Entities.FacultyMemberDataModule.FacultyMember", "FacultyMember")
                        .WithOne("ContactData")
                        .HasForeignKey("Domain.Entities.FacultyMemberDataModule.ContactData", "FacultyMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FacultyMember");
                });

            modelBuilder.Entity("Domain.Entities.FacultyMemberDataModule.IdentificationCard", b =>
                {
                    b.HasOne("Domain.Entities.FacultyMemberDataModule.FacultyMember", "FacultyMember")
                        .WithOne("IdentificationCard")
                        .HasForeignKey("Domain.Entities.FacultyMemberDataModule.IdentificationCard", "FacultyMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FacultyMember");
                });

            modelBuilder.Entity("Domain.Entities.FacultyMemberDataModule.PersonalData", b =>
                {
                    b.HasOne("Domain.Entities.Lookup", "Authority")
                        .WithMany()
                        .HasForeignKey("AuthorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Lookup", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.FacultyMemberDataModule.FacultyMember", "FacultyMember")
                        .WithOne("PersonalData")
                        .HasForeignKey("Domain.Entities.FacultyMemberDataModule.PersonalData", "FacultyMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Lookup", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Lookup", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Lookup", "MaritalStatus")
                        .WithMany()
                        .HasForeignKey("MaritalStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Lookup", "Title")
                        .WithMany()
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Lookup", "University")
                        .WithMany()
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Authority");

                    b.Navigation("Department");

                    b.Navigation("FacultyMember");

                    b.Navigation("Field");

                    b.Navigation("Gender");

                    b.Navigation("MaritalStatus");

                    b.Navigation("Title");

                    b.Navigation("University");
                });

            modelBuilder.Entity("Domain.Entities.FacultyMemberDataModule.SocialMediaPlatforms", b =>
                {
                    b.HasOne("Domain.Entities.FacultyMemberDataModule.FacultyMember", "FacultyMember")
                        .WithOne("SocialMediaPlatforms")
                        .HasForeignKey("Domain.Entities.FacultyMemberDataModule.SocialMediaPlatforms", "FacultyMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FacultyMember");
                });

            modelBuilder.Entity("Domain.Entities.MissionsModule.ConferencesAndSeminars", b =>
                {
                    b.HasOne("Domain.Entities.FacultyMemberDataModule.FacultyMember", "FacultyMember")
                        .WithMany("ConferencesAndSeminars")
                        .HasForeignKey("FacultyMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Lookup", "RoleOfParticipation")
                        .WithMany()
                        .HasForeignKey("RoleOfParticipationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FacultyMember");

                    b.Navigation("RoleOfParticipation");
                });

            modelBuilder.Entity("Domain.Entities.MissionsModule.ScientificMissions", b =>
                {
                    b.HasOne("Domain.Entities.FacultyMemberDataModule.FacultyMember", "FacultyMember")
                        .WithMany("ScientificMissions")
                        .HasForeignKey("FacultyMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FacultyMember");
                });

            modelBuilder.Entity("Domain.Entities.MissionsModule.TrainingPrograms", b =>
                {
                    b.HasOne("Domain.Entities.FacultyMemberDataModule.FacultyMember", "FacultyMember")
                        .WithMany("TrainingPrograms")
                        .HasForeignKey("FacultyMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FacultyMember");
                });

            modelBuilder.Entity("Domain.Entities.ProjectsAndCommitteesModule.CommitteesAndAssociations", b =>
                {
                    b.HasOne("Domain.Entities.Lookup", "DegreeOfSubscription")
                        .WithMany()
                        .HasForeignKey("DegreeOfSubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.FacultyMemberDataModule.FacultyMember", "FacultyMember")
                        .WithMany("CommitteesAndAssociations")
                        .HasForeignKey("FacultyMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Lookup", "TypeOfCommitteeOrAssociation")
                        .WithMany()
                        .HasForeignKey("TypeOfCommitteeOrAssociationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DegreeOfSubscription");

                    b.Navigation("FacultyMember");

                    b.Navigation("TypeOfCommitteeOrAssociation");
                });

            modelBuilder.Entity("Domain.Entities.ProjectsAndCommitteesModule.ParticipationInMagazines", b =>
                {
                    b.HasOne("Domain.Entities.FacultyMemberDataModule.FacultyMember", "FacultyMember")
                        .WithMany("ParticipationInMagazines")
                        .HasForeignKey("FacultyMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Lookup", "TypeOfParticipation")
                        .WithMany()
                        .HasForeignKey("TypeOfParticipationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FacultyMember");

                    b.Navigation("TypeOfParticipation");
                });

            modelBuilder.Entity("Domain.Entities.ProjectsAndCommitteesModule.Projects", b =>
                {
                    b.HasOne("Domain.Entities.FacultyMemberDataModule.FacultyMember", "FacultyMember")
                        .WithMany("Projects")
                        .HasForeignKey("FacultyMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Lookup", "ParticipationRole")
                        .WithMany()
                        .HasForeignKey("ParticipationRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Lookup", "TypeOfProject")
                        .WithMany()
                        .HasForeignKey("TypeOfProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FacultyMember");

                    b.Navigation("ParticipationRole");

                    b.Navigation("TypeOfProject");
                });

            modelBuilder.Entity("Domain.Entities.ProjectsAndCommitteesModule.ReviewingArticles", b =>
                {
                    b.HasOne("Domain.Entities.FacultyMemberDataModule.FacultyMember", "FacultyMember")
                        .WithMany("ReviewingArticles")
                        .HasForeignKey("FacultyMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FacultyMember");
                });

            modelBuilder.Entity("Domain.Entities.ScientificProgressionModule.AcademicQualifications", b =>
                {
                    b.HasOne("Domain.Entities.Lookup", "DispatchType")
                        .WithMany()
                        .HasForeignKey("DispatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.FacultyMemberDataModule.FacultyMember", "FacultyMember")
                        .WithMany("AcademicQualifications")
                        .HasForeignKey("FacultyMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Lookup", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Lookup", "Qualification")
                        .WithMany()
                        .HasForeignKey("QualificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DispatchType");

                    b.Navigation("FacultyMember");

                    b.Navigation("Grade");

                    b.Navigation("Qualification");
                });

            modelBuilder.Entity("Domain.Entities.ScientificProgressionModule.AdministrativePositions", b =>
                {
                    b.HasOne("Domain.Entities.FacultyMemberDataModule.FacultyMember", "FacultyMember")
                        .WithMany("AdministrativePositions")
                        .HasForeignKey("FacultyMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FacultyMember");
                });

            modelBuilder.Entity("Domain.Entities.ScientificProgressionModule.JobRanks", b =>
                {
                    b.HasOne("Domain.Entities.FacultyMemberDataModule.FacultyMember", "FacultyMember")
                        .WithMany("JobRanks")
                        .HasForeignKey("FacultyMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Lookup", "JobRank")
                        .WithMany()
                        .HasForeignKey("JobRankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FacultyMember");

                    b.Navigation("JobRank");
                });

            modelBuilder.Entity("Domain.Entities.FacultyMemberDataModule.FacultyMember", b =>
                {
                    b.Navigation("AcademicQualifications");

                    b.Navigation("AdministrativePositions");

                    b.Navigation("CommitteesAndAssociations");

                    b.Navigation("ConferencesAndSeminars");

                    b.Navigation("ContactData");

                    b.Navigation("IdentificationCard");

                    b.Navigation("JobRanks");

                    b.Navigation("ParticipationInMagazines");

                    b.Navigation("PersonalData");

                    b.Navigation("Projects");

                    b.Navigation("ReviewingArticles");

                    b.Navigation("ScientificMissions");

                    b.Navigation("SocialMediaPlatforms");

                    b.Navigation("TrainingPrograms");
                });
#pragma warning restore 612, 618
        }
    }
}
