// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Presistence.Data;

#nullable disable

namespace Presistence.Data.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20251114154452_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.FacultyMemberData.ContactData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("NVARCHAR(75)");

                    b.Property<string>("AlternativeEmail")
                        .HasColumnType("NVARCHAR(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FacultyMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FaxNumber")
                        .HasColumnType("NVARCHAR(150)");

                    b.Property<string>("HomePhoneNumber")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MainPhoneNumber")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("OfficialEmail")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(150)");

                    b.Property<string>("PersonalEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.Property<string>("WorkPhoneNumber")
                        .HasColumnType("NVARCHAR(50)");

                    b.HasKey("Id");

                    b.HasIndex("FacultyMemberId")
                        .IsUnique();

                    b.HasIndex("MainPhoneNumber");

                    b.HasIndex("OfficialEmail");

                    b.ToTable("ContactData");
                });

            modelBuilder.Entity("Domain.Entities.FacultyMemberData.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FieldOfStudyId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FieldOfStudyId", "DepartmentName")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Domain.Entities.FacultyMemberData.Faculty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacultyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("UniversityId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("Domain.Entities.FacultyMemberData.FacultyMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(150)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NationalNumber")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(14)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("SpecializationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.HasIndex("NationalNumber")
                        .IsUnique();

                    b.HasIndex("SpecializationId");

                    b.ToTable("FacultyMembers");
                });

            modelBuilder.Entity("Domain.Entities.FacultyMemberData.FieldOfStudy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<string>("FieldOfStudyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("FieldOfStudies");
                });

            modelBuilder.Entity("Domain.Entities.FacultyMemberData.IdentificationCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademiaEdu")
                        .HasColumnType("NVARCHAR(Max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EKB")
                        .HasColumnType("NVARCHAR(Max)");

                    b.Property<Guid>("FacultyMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ORCID")
                        .HasColumnType("NVARCHAR(Max)");

                    b.Property<string>("ResearcherGate")
                        .HasColumnType("NVARCHAR(Max)");

                    b.Property<string>("ResearcherId")
                        .HasColumnType("NVARCHAR(Max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FacultyMemberId")
                        .IsUnique();

                    b.ToTable("IdentificationCards", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.FacultyMemberData.PersonalData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("Date");

                    b.Property<string>("BirthPlace")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CompositionTopics")
                        .HasColumnType("NVARCHAR(Max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FacultyMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NameInComposition")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SocialStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FacultyMemberId")
                        .IsUnique();

                    b.ToTable("PersonalData");
                });

            modelBuilder.Entity("Domain.Entities.FacultyMemberData.SocialMediaPlatforms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Facebook")
                        .HasColumnType("NVARCHAR(Max)");

                    b.Property<Guid>("FacultyMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GoogleScholar")
                        .HasColumnType("NVARCHAR(Max)");

                    b.Property<string>("Instagram")
                        .HasColumnType("NVARCHAR(Max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LinkedIn")
                        .HasColumnType("NVARCHAR(Max)");

                    b.Property<string>("PersonalWebsite")
                        .HasColumnType("NVARCHAR(Max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Scopus")
                        .HasColumnType("NVARCHAR(Max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.Property<string>("X")
                        .HasColumnType("NVARCHAR(Max)");

                    b.Property<string>("YouTube")
                        .HasColumnType("NVARCHAR(Max)");

                    b.HasKey("Id");

                    b.HasIndex("FacultyMemberId")
                        .IsUnique();

                    b.ToTable("SocialMedia", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.FacultyMemberData.Specialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccurateSpecialization")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("GeneralSpecialization")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId", "GeneralSpecialization");

                    b.ToTable("Specializations");
                });

            modelBuilder.Entity("Domain.Entities.FacultyMemberData.University", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UniversityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UniversityName")
                        .IsUnique();

                    b.ToTable("Universities");
                });

            modelBuilder.Entity("Domain.Entities.ResearchesModule.Theses_Supervision.Theses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("EnrollmentDate")
                        .HasColumnType("DATE");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<DateOnly?>("InternalGradeDate")
                        .HasColumnType("DATE");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("RegistrationDate")
                        .HasColumnType("DATE");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("StudentMajor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("StudentNationalNumber")
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR(14)");

                    b.Property<DateOnly?>("SupervisionConfirmationDate")
                        .HasColumnType("DATE");

                    b.Property<string>("ThesesInEnglishHyperLink")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("ThesesType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentDate");

                    b.HasIndex("StudentName");

                    b.HasIndex("StudentNationalNumber")
                        .IsUnique()
                        .HasFilter("[StudentNationalNumber] IS NOT NULL");

                    b.HasIndex("ThesesType");

                    b.ToTable("Theses");
                });

            modelBuilder.Entity("Domain.Entities.ResearchesModule.Theses_Supervision.ThesesSupervision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DiscussionDate")
                        .HasColumnType("DATE");

                    b.Property<DateOnly?>("GrantingDate")
                        .HasColumnType("DATE");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("RegistrationDate")
                        .HasColumnType("DATE");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateOnly?>("SupervisionFormationDate")
                        .HasColumnType("DATE");

                    b.Property<int>("ThesesId")
                        .HasColumnType("int");

                    b.Property<int>("ThesesSupervisorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ThesesId");

                    b.HasIndex("ThesesSupervisorId");

                    b.ToTable("ThesesSupervisions");
                });

            modelBuilder.Entity("Domain.Entities.ResearchesModule.Theses_Supervision.ThesesSupervisor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Authority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FacultyMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("JobLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FacultyMemberId");

                    b.HasIndex("Name");

                    b.ToTable("ThesesSupervisors");
                });

            modelBuilder.Entity("Domain.Entities.FacultyMemberData.ContactData", b =>
                {
                    b.HasOne("Domain.Entities.FacultyMemberData.FacultyMember", "FacultyMember")
                        .WithOne("ContactData")
                        .HasForeignKey("Domain.Entities.FacultyMemberData.ContactData", "FacultyMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FacultyMember");
                });

            modelBuilder.Entity("Domain.Entities.FacultyMemberData.Department", b =>
                {
                    b.HasOne("Domain.Entities.FacultyMemberData.FieldOfStudy", "FieldOfStudy")
                        .WithMany("Departments")
                        .HasForeignKey("FieldOfStudyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FieldOfStudy");
                });

            modelBuilder.Entity("Domain.Entities.FacultyMemberData.Faculty", b =>
                {
                    b.HasOne("Domain.Entities.FacultyMemberData.University", "University")
                        .WithMany("Faculties")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("Domain.Entities.FacultyMemberData.FacultyMember", b =>
                {
                    b.HasOne("Domain.Entities.FacultyMemberData.Specialization", "Specialization")
                        .WithMany("FacultyMembers")
                        .HasForeignKey("SpecializationId");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("Domain.Entities.FacultyMemberData.FieldOfStudy", b =>
                {
                    b.HasOne("Domain.Entities.FacultyMemberData.Faculty", "Faculty")
                        .WithMany("FieldsOfStudy")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("Domain.Entities.FacultyMemberData.IdentificationCard", b =>
                {
                    b.HasOne("Domain.Entities.FacultyMemberData.FacultyMember", "FacultyMember")
                        .WithOne("IdentificationCard")
                        .HasForeignKey("Domain.Entities.FacultyMemberData.IdentificationCard", "FacultyMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FacultyMember");
                });

            modelBuilder.Entity("Domain.Entities.FacultyMemberData.PersonalData", b =>
                {
                    b.HasOne("Domain.Entities.FacultyMemberData.FacultyMember", "FacultyMember")
                        .WithOne("PersonalData")
                        .HasForeignKey("Domain.Entities.FacultyMemberData.PersonalData", "FacultyMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FacultyMember");
                });

            modelBuilder.Entity("Domain.Entities.FacultyMemberData.SocialMediaPlatforms", b =>
                {
                    b.HasOne("Domain.Entities.FacultyMemberData.FacultyMember", "FacultyMember")
                        .WithOne("SocialMediaPlatforms")
                        .HasForeignKey("Domain.Entities.FacultyMemberData.SocialMediaPlatforms", "FacultyMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FacultyMember");
                });

            modelBuilder.Entity("Domain.Entities.FacultyMemberData.Specialization", b =>
                {
                    b.HasOne("Domain.Entities.FacultyMemberData.Department", "Department")
                        .WithMany("Specializations")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Domain.Entities.ResearchesModule.Theses_Supervision.ThesesSupervision", b =>
                {
                    b.HasOne("Domain.Entities.ResearchesModule.Theses_Supervision.Theses", "Theses")
                        .WithMany("Supervisions")
                        .HasForeignKey("ThesesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ResearchesModule.Theses_Supervision.ThesesSupervisor", "ThesesSupervisor")
                        .WithMany("ThesesSupervisions")
                        .HasForeignKey("ThesesSupervisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Theses");

                    b.Navigation("ThesesSupervisor");
                });

            modelBuilder.Entity("Domain.Entities.ResearchesModule.Theses_Supervision.ThesesSupervisor", b =>
                {
                    b.HasOne("Domain.Entities.FacultyMemberData.FacultyMember", "FacultyMember")
                        .WithMany()
                        .HasForeignKey("FacultyMemberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FacultyMember");
                });

            modelBuilder.Entity("Domain.Entities.FacultyMemberData.Department", b =>
                {
                    b.Navigation("Specializations");
                });

            modelBuilder.Entity("Domain.Entities.FacultyMemberData.Faculty", b =>
                {
                    b.Navigation("FieldsOfStudy");
                });

            modelBuilder.Entity("Domain.Entities.FacultyMemberData.FacultyMember", b =>
                {
                    b.Navigation("ContactData");

                    b.Navigation("IdentificationCard");

                    b.Navigation("PersonalData");

                    b.Navigation("SocialMediaPlatforms");
                });

            modelBuilder.Entity("Domain.Entities.FacultyMemberData.FieldOfStudy", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("Domain.Entities.FacultyMemberData.Specialization", b =>
                {
                    b.Navigation("FacultyMembers");
                });

            modelBuilder.Entity("Domain.Entities.FacultyMemberData.University", b =>
                {
                    b.Navigation("Faculties");
                });

            modelBuilder.Entity("Domain.Entities.ResearchesModule.Theses_Supervision.Theses", b =>
                {
                    b.Navigation("Supervisions");
                });

            modelBuilder.Entity("Domain.Entities.ResearchesModule.Theses_Supervision.ThesesSupervisor", b =>
                {
                    b.Navigation("ThesesSupervisions");
                });
#pragma warning restore 612, 618
        }
    }
}
